data: 
  numeric: [
    "duration_in_month",
    "credit_amount",
    "installment_as_income_perc",
    "present_residence_since",
    "age",
    "credits_this_bank",
    "people_under_maintenance"
  ]
  category: [
    "default",
    "account_check_status",
    "credit_history",
    "purpose",
    "savings",
    "present_employment_since",
    "sex",
    "personal_status",
    "other_debtors",
    "property",
    "other_installment_plans",
    "housing",
    "job",
    "telephone",
    "foreign_worker"
  ]
  target: default 
  reference: Default
  classification: true
  test_prop: .2
  batch_size: 32
  logit_transform: false
model: 
  input_layer: 
    [[Linear, 47, 512],     # number of input features
    [Dropout, 0.1], 
    [ReLU]]
  hidden_layers: 
    [[Linear, 512, 256], 
    [Dropout, 0.1], 
    [ReLU]]
  output_layer:
    [[Linear, 256, 47]]      # number of input features
training: 
  n_epochs: 50000
  n_iters: 10000000000000
  noise_std: 0.01
  n_particles: 1
  algo: "dsm"
  snapshot_freq: 30000
  eval_freq: 500
  resume_training: false
optim:
  optimizer: 
    weight_decay: 0.000
    name: "Adam"
    lr: 0.001
    beta1: 0.9
  scheduler: 
    name: ExponentialLR
    gamma: .9
  use_scheduler: false
sampling: 
  langevin: 
    n_steps: 1000
    step_lr: 0.00002
    n_batches: 1
device: cpu
backup_dir: models/credit/scorenetdsm